const data = {
    products:[
        {
            _id: '1',
            name:'Diwali',
            category:'Festival',
            image:'/images/D1.jpg',
            price: 200,
            countInStock: 10,
            brand:'Diwali',
            rating:4.5,
            numReview:10,
            description:'high quality Image',
        },
        {
            _id: '2',
            name:'Diwali',
            category:'Festival',
            image:'/images/D2.jpg',
            price: 250,
            countInStock: 20,
            brand:'Diwali',
            rating:4.0,
            numReview:12,
            description:'high quality Image',
        },
        {
            _id: '3',
            name:'Diwali',
            category:'Festival',
            image:'/images/D3.jpg',
            price: 180,
            countInStock: 0,
            brand:'Diwali',
            rating:4.8,
            numReview:17,
            description:'high quality Image',
        },
        {
            _id: '4',
            name:'Diwali',
            category:'Festival',
            image:'/images/D4.jpg',
            price: 300,
            countInStock: 15,
            brand:'Diwali',
            rating:4.5,
            numReview:14,
            description:'high quality Image',
        },
        {
            _id: '5',
            name:'Diwali',
            category:'Festival',
            image:'/images/D5.jpg',
            price: 150,
            countInStock: 5,
            brand:'Diwali',
            rating:4.5,
            numReview:10,
            description:'high quality Image',
        },
        {
            _id: '6',
            name:'Diwali',
            category:'Festival',
            image:'/images/D6.jpg',
            price: 280,
            countInStock: 12,
            brand:'Diwali',
            rating:4.5,
            numReview:15,
            description:'high quality Image',
        },
    ],
};
export default data;
